name: advent
description: Advent of Code 2019 solutions
version: 1.0.0
author: Björn Petersen <pheasn@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  async: ^2.4.0
  path: ^1.6.0
  sprintf: ^4.0.0
  args: ^1.5.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
