name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:2.6

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test

  dartanalyzer:
    runs-on: ubuntu-latest

    container:
      image: google/dart:2.6

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Analyze project
        run: dartanalyzer --fatal-warnings --fatal-infos .
